### ISSUE TITLE
Documentation Error

### ISSUE THREAD

**Issue by B2Pi** [p5-shorten/WWW-Shorten-Bitly#1]
The documentation for expand is quite wrong, or points that it was meant to do some of the postprocessing on the result that makealongerlink does.

The following patch causes things to match the docs, as well as a couple of small problems in  the new method

```
--- /usr/local/lib/perl5/site_perl/WWW/Shorten/Bitly.pm 2016-09-16 22:51:56.000000000 -0400
+++ ./Bitly.pm  2017-02-06 14:35:09.589127000 -0500
@@ -153,7 +153,7 @@
     # start with what's in our config file (if anything)
     my $href = _parse_config();
     # override with anything passed in
-    for my $key (%{$args}) {
+    for my $key (keys %{$args}) {
         my $lc_key = lc($key);
         $lc_key = 'username' if $lc_key eq 'user';
         next unless grep {$lc_key eq $_} @{$attrs};
@@ -267,8 +267,11 @@
         shortUrl => $short_url,
         hash => $args->{hash},
         format => 'json',
-    );
-    return _json_request($url);
+       );
+
+    my $res = _json_request($url);
+    Carp::croak("Invalid response") unless $res && ref($res->{expand}) eq 'ARRAY';
+    return $res->{expand}[0];
 }

 sub info {
@@ -375,12 +378,9 @@
     }
     my $url = shift or Carp::croak('No URL passed to makealongerlink');
     $self ||= __PACKAGE__->new(@_);
-    my $res = $self->expand(shortUrl=>$url, @_);
-    return '' unless ref($res->{expand}) eq 'ARRAY';
-    for my $row (@{$res->{expand}}) {
-        return $row->{long_url};
-    }
-    return '';
+    my $res = $self->expand(shortUrl=>$url);
+    return '' unless ref($res) eq 'HASH' and $res->{long_url};
+    return $res->{long_url};
 }

 sub password { return shift->_attr('password', @_); }
```

Cheers

**Comment by genio** [comment]
Hi @B2Pi   Thanks for finding the issue!  Would you mind working it up into a PR so that it can be tested? Also, your work would be acknowledged via the build process in the contributors meta information.

**Comment by B2Pi** [comment]
I've not done anything on CPAN for about 20 years. What's a PR?

Cheers

**Comment by genio** [comment]
Sorry, that's just an abbreviation for [Pull Request](https://help.github.com/articles/about-pull-requests/). It's a way to propose a code change in a git repository that allows collaboration and allows the automated testing to hit your changes as well.

Then, if the changes are accepted, your code gets pulled into the repository and your name shows up in the history. You're actually contributing code to the source.  A diff patch accomplishes the same thing in the end, but kind of less collaboratively and doesn't really give credit to the one that did the work.

As for working with the CPAN, you still wouldn't have to.  I'd accept the changes, re-build the dist (which would then have you as a collaborator) and push a new build to the CPAN.

**Comment by genio** [comment]
If this isn't something you're comfortable with, I'll be happy to just make the changes, but I prefer to leave a trail of credit for the work of others where possible.  Just let me know.

**Comment by genio** [comment]
Thank you again for the fix.  It has been released: [WWW::Shorten::Bitly](https://metacpan.org/release/CAPOEIRAB/WWW-Shorten-Bitly-2.001)
